[project]
name = "mongo-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.2.0",
    "langchain>=1.2.10",
    "langchain-community>=0.4.1",
    "langchain-groq>=1.1.2",
    "langchain-openai>=1.1.10",
    "openai>=2.24.0",
    "pymongo>=4.16.0",
    "pypdf>=6.7.4",
    "python-dotenv>=1.2.1",
]
